
physics_engine: "physx"
pipeline: "gpu"
sim_device: "cuda:0"
rl_device: "cuda:0"
graphics_device_id: 0
num_gpus: 1

# 1.Change net_type
net_type: "ann"
# 2.Change logdir
logdir: "./log/KukaPick_ann"

snn_max_iterations: 4000
ann_max_iterations: 2000

test: False
resume: 0

cptdir: ""
headless: True

defaults:
# 3.Change task
  - task: KukaPick
  - train: ${task}
  - hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .
